### ISSUE TITLE
[Feature request] Better logging

### ISSUE THREAD

**Issue by Civil** [dgryski/carbonapi#143] opened 2016-08-18 13:12 UTC
I think carbonapi should have separate access.log which should ideally have request URI, extra parameters in case it's POST, time it took to process (everything excluding returning data to client), full time (including time it took to send data to the client), HTTP return code, amount of carbonzipper requests it produced and some timestamp (not necessary human readable).

**Comment by JaderDias** [comment] 2016-08-20 21:03
This issue is a duplicate of https://github.com/dgryski/carbonapi/issues/126

**Closed** 2016-08-20 21:03 UTC
